### ISSUE TITLE
'modinfo' error

### ISSUE THREAD

**Issue by coolternet** [spravil/PHP-Minecraft-Server-Status-Query#47]
`Catchable fatal error: Object of class stdClass could not be converted to string on line 46`

line 46 : <p><?php echo $response['modinfo']; ?></p> <br />

same things for : <p>MOTD detail : <?php echo $response['description_raw']; ?></p> <br />

**Comment by Codewow** [comment]
Try converting it to a string like so:

echo $response['modinfo']->text;
and
echo $response['description_raw']->text;
